[package]
name = "rust_signal_and_slots"
version = "0.1.0"
authors = ["Jonas Mucke <jonas.mucke@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"

